### ISSUE TITLE
rights check on items under research/video-bibliography.md

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#12]
Depending on how these are used in the video, we may need to seek permissions to use:

01:48 Charles L. Franck Photographers. The Historic New Orleans Collection / Charles L. Franck and Franck-Bertacci Photograph Collections. View down the 100 Block of Elk Place from Common Street. ca. 1936. https://louisianadigitallibrary.org/islandora/object/hnoc-clf%3A10164
[Contact The Historic New Orleans Collection for more information about use and reproduction. louisquery@hnoc.org]

01:59 DEULIG TON - WOCHE NO. 59 Library of Congress Moving Image Division. Call no. FAB 6423, database entry no. 59306. ca. 1933.
[request copyright status with moving image division staff]

05:26 Jibboom Street, Truckee, 1870. Jennings, Sherry E. Truckee. Charleston, S.C.: Arcadia Pub, 2011. Photograph.
[photograph in a book? origin of photograph known?]

**Comment by jaimemears** [comment]
Jeff is going to check on the Elk Street Photograph- based on cars it looks like its pre-1927 (model As)
Jaime will follow up about Dulig ton- woche no. 59
Jeff will follow up on Jibboom Street photo - pre-copyright but no info on creator so far

**Comment by jywarren** [comment]
Updates: Jibboom is originally via Donner Truckee Historical Society. Deulig etc is public domain. Elk Street still working on.

**Comment by jywarren** [comment]
Resolved - replaced image for now!
