### ISSUE TITLE
Copyright/ citation check for https://github.com/jywarren/seeing-lost-enclaves/blob/main/research/images/images-central-baptist.png

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#14]
This will be based on what we hear back from social media working group. Need to make sure none of these images are copyrighted. Books featured cited if possible, especially the one on the left with text.

**Comment by jywarren** [comment]
will look for alternative image - all photos are pre-1914 but State Archives have limited metadata and none online

**Comment by jywarren** [comment]
"transformative fair use" and/or public domain -- all good!
