### ISSUE TITLE
Updating sign up link on soundscapes/index.md and contact page

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#21]
As an evergreen Library product, what's the most appropriate strategy for links back to your personal site? I'm thinking we point from soundscapes/index.md to the contact page, and update contact page with options for signing up with Labs, or visiting your personal website, following on social media, etc, with clear demarcations between your web properties and the Library's.

For reference, experiments page currently says -
Sign up for our Lost Enclaves distribution list to hear about project releases and events by sending us an email at LC-Labs@loc.gov. You can also follow #SeeingLostEnclaves on social media - @LC_Labs and @jywarren on Twitter, and @librarycongress and @unterbahn on Instagram.

**Comment by jywarren** [comment]
at https://jywarren.github.io/seeing-lost-enclaves/#contact -- right? OK! Doing this now.
