### ISSUE TITLE
Updating blog page/ LE publications

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#22]
should point to published blogs on The Signal. What's the most user-friendly way to do that and keep it up to date as we publish more? Do press releases and other media things go here, or do they get listed on https://labs-dev.loc.gov/work/experiments/lost-enclaves/

https://blogs.loc.gov/thesignal/?new=true&s=jeffrey+yoo+warren

**Comment by jywarren** [comment]
added https://blogs.loc.gov/thesignal/?new=true&s=jeffrey+yoo+warren to front page!
