### ISSUE TITLE
QA links in repo for accessibility

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#25]
Full guide here  - https://staff.loc.gov/sites/digital-accessibility/guides/links/

UXD Checklist

- [x] Link text must have a minimum 4.5:1 contrast ratio with background.
- [x] Make links visually distinct from static text
- [x] Underline links
- [ ] Use link location
- [x] Use a minimum 3:1 contrast ratio with surrounding, static text and a style change on focus
- [x] Present links just one time per page (Minimize duplicate links)
- [x] Links must have text labels, including linked images
- [x] Link text must be meaningful and unique.
- [x] Link context must be visually clear
- [x] Link context must be programmatically clear
- [x] Identify format of linked documents
- [x] Identify external links
- [x] Avoid opening new tabs or windows
- [x] Consider a short url

Examples:
Meaningful & Unique Link Text
Link text must be meaningful and should be unique. Avoid generic text like “Learn more” or “Click here” which do not communicate the link purpose. Ideally, a user should be able to tell purpose based on link text alone.

Example: You are linking to two digital collections in a blog post. You use the collection names as the link text instead of two “view the collection” links.

Identify the document format
Identify the document format in the link text when linking to formats that aren’t webpages, like PDFs and MS Word. The easiest way to do this is to include the document formats in parenthesis after the link text.

Example: A webpage links to a PDF version of the Library’s strategic report. The link text is “2019-2023 Library of Congress Strategic Plan (PDF)”.

**Comment by jywarren** [comment]
```
<img src="https://chroniclingamerica.loc.gov/media/images/icon-ext-gray.edbef60e7b31.gif" alt="external link" style="display: inline;">
```

**Comment by jywarren** [comment]
Only for non-`loc.gov` type properties

**Comment by jywarren** [comment]
Noting from discussion: one thing on the external link markings, i'm relatively often including the full URL, which makes it clear without the marking. Since the marking makes the markdown less readable I'm inclined to leave it out where I've included a full URL.

It's a judgement call because removing "https://www/" makes it better for screen readers

so I guess it's between more readable in markdown, vs. more readable by screen readers... i guess i prefer the latter

so maybe i'll leave the markings in and remove "https://www/..."

i could leave markings out and also remove "https://www/", because you can still see the URL hostname

**Comment by jywarren** [comment]
Ultimately the markdown looks like this, which isn't awesome, but it looks good when rendered and isn't terrible. I could shorten the image filename to save space but it's not bad:

```
such as the one I have begun to craft in the [Seeing Providence Chinatown project](https://unterbahn.com/chinatown) *![external link](../images/external-link.gif)* (see below), about the neighborhood which existed
```

<img width="673" alt="image" src="https://github.com/jywarren/seeing-lost-enclaves/assets/24359/c4226489-1e7b-4d3a-a26f-12ef323cafd9">
