### ISSUE TITLE
QA for page organization and structure

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#26]
Reference: https://staff.loc.gov/sites/digital-accessibility/guides/page-organization-structure/

Accessible documents have a strong, clear organization and structure. Your document should be structured into content chunks. Each content chunk should include related information and be associated with a page section or heading.

When web pages and documents are well organized with clear headings, it is easier for users to navigate, use, and understand them.  For people with cognitive disabilities that affect memory and attention, this is particularly important as it helps them find information or reorient after losing where they are. Organized headings also help screen reader and other assistive technology users quickly navigate through content.

Page organization should be communicated visually and semantically. Semantic headings and content organization includes the code or formatting that lets assistive technologies recognize what they are.

Page organization and structure includes the following topics:

Regions: High level organization of a page into regions like page header, navigation, main content, and footer.
[Headings](https://staff.loc.gov/sites/digital-accessibility/guides/page-organization-structure/headings/): Labels that describe the content grouped beneath them.
Semantics: HTML, styles, tagging, and other programmatic means used in addition to visual elements such as size, weight, placement, and fonts to convey the content’s organization and structure.
Reading & Tab Order: The order assistive technology reads the content and the order the keyboard focus moves when advanced (typically using the tab key).

**Comment by jywarren** [comment]
Happy to discuss how this works for this project -- a major factor is that it is a linear design and uses standard Markdown heading hierarchy. Thanks!
