### ISSUE TITLE
LC logo

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#31]
It's been requested that we add official LC branding as a header for the toolkit. I have several variations of the LC logo but it seems like the one you designed with Marlena might work best? I've attached the LC logo in vertical as well.

![loc-logo-horizantal](https://github.com/jywarren/seeing-lost-enclaves/assets/22895272/07505b0f-091e-49f8-aed0-c689c9a0d3f7)

**Comment by jywarren** [comment]
Something like this or the project specific graphic:

<img width="941" alt="image" src="https://github.com/jywarren/seeing-lost-enclaves/assets/24359/49953d70-3883-4c1a-bbb8-4a5518f0898d">
