### ISSUE TITLE
G&M feedback for https://jywarren.github.io/seeing-lost-enclaves/#research/images.md

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#32]
- [x] **Tracking photos link is dead**
- [ ] **suggesting other types of maps beyond sanborns** that could be helpful - "could be useful to go into a little more depth about the range of maps outside of Sanborn that could be relevant (i.e., maps that might show changing street names, plot lines and building footprints, etc). Although Sanborn was the largest active producer of historical built-environment maps for the US, there were many other commercial producers of maps for fire insurance and real estate purposes. For fire insurance maps alone, LC's collections are listed in a 342-page bibliography (!) linked from https://guides.loc.gov/fire-insurance-maps/other-companies. Real estate atlases, or plat books, can also be excellent sources. These maps often have similar basic building information as that found on Sanborns and other fire insurance maps, minus some of the more detailed building information offered by Sanborns but with addresses that are more likely to be accurate (Sanborn often has estimated street numbers) and often with plot numbers. County land ownership atlases and city plans might also be especially relevant. Within LC's collections, digitized county land ownership maps can be found in this search for Part Of: County Landownership Maps https://www.loc.gov/maps/?fa=partof:county+landownership+maps. A sample of maps on the theme of "Cities and Town" have been digitized into the collection at https://www.loc.gov/collections/cities-and-towns/about-this-collection/. This digital collection includes examples  of insurance atlases, real estate atlases, city plans, etc. . Although it includes a handful of panoramic maps (aka birds-eye view drawings), many more of those can be found in the Panoramic Maps collection at https://loc.gov/collections/panoramic-maps/about-this-collection/. One note of caution with panoramic maps is that they can be particularly out of scale. Individual buildings or entire sections of town were sometimes selectively exaggerated in order to advertise a city's potential by the local chamber of commerce or other local civic organization, and the drawings sometimes depicted planned developments not yet realized (see https://www.loc.gov/collections/panoramic-maps/articles-and-essays/panoramic-mapping/).
- [ ] **search terms for locating maps** - When searching for maps, here are some terms that could be helpful for locating real estate, fire insurance, and other maps that are likely to have details about buildings, street addresses, property ownership, etc: insurance, fire insurance, landowners, landownership, real estate, real property, cadastral, plat, survey, plan. Planning maps can be great sources of information about changes to neighborhoods. Researchers' search might turn up drawings for proposed new streets, parks, and/or lot divisions, by developers who are looking to create new neighborhoods on top of existing land use. These maps can show information about the community that is planned for replacement/displacement. For example, the 1908 map at [Land in Hall and Elvan's subdivision of Meridian Hill, District of Columbia, for public park](http://hdl.loc.gov/loc.gmd/g3852m.ct005022) shows details about the property lots of the Black DC neighborhood that was raised and replaced by Meridian Hill Park beginning in the 1910s. If the erased neighborhood was replaced by a named neighborhood, searching by the name of the incoming/replacement neighborhood (or park) can also turn up maps that show the planned changes before they happened, for example maps like http://hdl.loc.gov/loc.gmd/g3852c.la002250 (showing expansion of the white "Meridian Hill" neighborhood, encroaching on the same Black neighborhood) or http://hdl.loc.gov/loc.gmd/g3852l.la002315 (proposed road redesigns for a new "Lanier Heights" neighborhood). These maps can show the pre-existing lots (and possibly other details) alongside their intersection points with planned new roads, parks, or new lots. Many planning maps in LC's collections show un-realized plans to redevelop "slums" or "undeveloped" land even before the 20th century.

**Comment by jywarren** [comment]
Created a page for this, checking about use of exact text & attribution before pushing it up.
