### ISSUE TITLE
PnP feedback for https://jywarren.github.io/seeing-lost-enclaves/#research/images.md 

### ISSUE THREAD

**Issue by jaimemears** [jywarren/seeing-lost-enclaves#34]
- [x] "These search terms can also work in the Library of Congress's various search systems, such as the [Prints and Photos Division search](https://www.loc.gov/photos/)." - [note from Adam] - _The Prints & Photographs Online Catalog. Then link to https://loc.gov/pictures/_
- [ ] ~""Deadwood, [S.D.] from Mrs. Livingston's Hill” by John C. H. Grabill, between 1887-92, [Library of Congress](https://www.loc.gov/item/99613869/). The area of Chinatown can be seen in the distance. See [Mapping photos](https://jywarren.github.io/seeing-lost-enclaves/#/research/mapping.md) for more on this image." - [note from Adam] - _Please include URL for the item in caption. Recommended caption (not necessary to use exactly): Deadwood, [S.D.] from Mrs. Livingston’s Hill, ca. 1887-1892. Photograph by John C.H. Grabill. Library of Congress, Prints & Photographs Division, https://lccn.loc.gov/99613869._~
- [x] "Bear in mind that not all images in collections have been digitized or are accessible online. Many are not even catalogued. Visiting archives in person almost always turns up details, materials, and new clues. See Physical archives below." - [note from Adam] - _Everything is cataloged, meaning that every photograph will at least have a catalog record at the collection level. Everything is not cataloged at the item level._
- [x] "In the [Prints and Photos Division](https://www.loc.gov/pictures/), several collections are only available in person," - [note from Adam] - _Only a minority online currently unfortunately. I’d say something like “currently many collections are only available in person, although more an more is being scanned and made available online.”_
- [x] [note from Adam] - _Not sure if the Providence broadsides came from Chronicling America or not. At the bottom of this page is how to cite from CA: [Help « Chronicling America « Library of Congress (loc.gov)](https://chroniclingamerica.loc.gov/help/)._

**Comment by jywarren** [comment]
Regarding no 2 (https://lccn.loc.gov/99613869.), I believe in this case, in a caption, accessibility best practices are to use a descriptive text rather than a plaintext link. I'd like to do this site-wide even though it's not citation format standard, because screen readers will take a very long time to read plaintext URLs.
